{{- if .Values.enabled }}

{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jenkins.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
  annotations:
{{- if eq .Values.global.clusterType  "OCP" }}
    serviceaccounts.openshift.io/oauth-redirectreference.jenkins: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{ template "jenkins.name" .}}"}}'
{{- end }}
  labels:
    "app.kubernetes.io/name": '{{ template "jenkins.name" .}}'
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
---
apiVersion: v1
groupNames: null
kind: RoleBinding
metadata:
  labels:
    "app.kubernetes.io/name": '{{ template "jenkins.name" .}}'
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
  name: {{ include "jenkins.serviceAccountName" . }}_edit
roleRef:
  name: edit
subjects:
- kind: ServiceAccount
  name: {{ include "jenkins.serviceAccountName" . }}

{{ end }}
{{ end }}
