{{- if eq .Values.global.jenkins_enabled true }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/dependencies: '[{"name": "{{template "jenkins.name" . }}-jnlp",
        "namespace": "", "kind": "Service"}]'
    service.openshift.io/infrastructure: "true"
  name: {{template "jenkins.name" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    "app.kubernetes.io/name": '{{ template "jenkins.name" .}}'
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
spec:
  ports:
  - name: web
    nodePort: 0
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    name: {{template "jenkins.name" . }}
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{template "jenkins.name" . }}-jnlp
  namespace: {{ .Values.global.namespace }}
  labels:
    "app.kubernetes.io/name": '{{ template "jenkins.name" .}}'
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  ports:
  - name: agent
    nodePort: 0
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    name: {{template "jenkins.name" . }}
  sessionAffinity: None
  type: ClusterIP
{{- end }}



