{{- if eq .Values.global.sonar_enabled true }}
---
apiVersion: v1
kind: ImageStream
metadata:
  labels:
    build: {{ template "sonarqube.name" . }}
    app: {{ template "sonarqube.name" . }}
  name: {{ template "sonarqube.name" . }}
  namespace: {{ .Values.global.namespace }}
---
  apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    build: {{ template "sonarqube.name" . }}
    app: {{ template "sonarqube.name" . }}
    type: "image"
  name: {{ template "sonarqube.name" . }}
  namespace: {{ .Values.global.namespace }}
spec:
  nodeSelector:
  output:
    to:
      kind: ImageStreamTag
      name: {{ template "sonarqube.name" . }}:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: "{{ .Values.build.source_context_dir }}"
    git:
      ref: "{{ .Values.build.source_repository_ref }}"
      uri: "{{ .Values.build.source_repository_url }}"
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: {{ .Values.build.from_docker_image_registry_url }}:{{ .Values.build.from_docker_tag }}
  triggers:
  - type: ConfigChange
  - type: ImageChange

{{- end }}

